### ISSUE TITLE
`make install` does not install headers

### ISSUE THREAD

**Issue by rekado** [BSeppke/vigra_c#1]
Hi,

vigra_c is packaged for Guix, but when I wanted to use it to build Guile CV I noticed that only the shared library is installed by the `make install` target.  None of the headers are installed, so dependent packages cannot find it.

~~ Ricardo

**Comment by BSeppke** [comment]
Thanks for the info. Currently, depending packages often use the vigra_c lib as a submodule and thus do not install vigra_c. But since GuileCV seems to do so, I added the headers for installation as well in commit e81e12a . Please tell if this is sufficient for you or enhance it and add a pull request.

Kind regards, 
Benjamin
